-- ============================================
-- BuilderStack: Fresh seed data
-- 41 Website Creation / No-Code tools
-- Generated from website_no_code_.xlsx
-- ============================================

-- Clear all existing tools
TRUNCATE TABLE tools RESTART IDENTITY;

-- Insert all 41 tools
INSERT INTO tools (name, slug, short_description, long_description, category, pricing_model, budget_level, rating, website_link, is_sponsored) VALUES
  ('Webflow', 'webflow', 'Visual builder for responsive sites with CMS and hosting.', 'Visual builder for responsive sites with CMS and hosting. Best for: excels in professional portfolios, marketing sites, e-commerce with animations/SEO.. Pricing: Free; Site $14/mo; CMS $23/mo; Business $39/mo.', 'Website Creation', 'freemium', 'low', 4.5, 'https://webflow.com', false),
  ('Bubble', 'bubble', 'Balances power and ease for complex web apps.', 'Balances power and ease for complex web apps. Best for: ideal for marketplaces, SaaS MVPs, dynamic apps with databases/workflows.. Pricing: Free; Starter $32/mo; Growth $134/mo; Team $349/mo.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://bubble.io', false),
  ('Softr', 'softr', 'Turns Airtable/Google Sheets into web apps and portals.', 'Turns Airtable/Google Sheets into web apps and portals. Best for: perfect for client dashboards, internal tools, membership sites with auth.. Pricing: Free; Basic $49/mo; Pro $139/mo; Business $269/mo.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://softr.io', false),
  ('Framer', 'framer', 'Focuses on portfolios with animations and templates.', 'Focuses on portfolios with animations and templates. Best for: great for designers building interactive landing pages/microsites.. Pricing: Free; Basic $10/mo; Pro $30/mo; Scale $100/mo.', 'Website Creation', 'freemium', 'low', 4.5, 'https://framer.com', false),
  ('Emergent', 'emergent', 'AI-powered full-stack builder using natural language.', 'AI-powered full-stack builder using natural language. Best for: suits rapid prototyping of custom apps without design skills.. Pricing: Not specified (AI-focused) emergent.', 'Website Creation', 'unknown', 'medium', 4.5, 'https://emergent.sh', false),
  ('Wix', 'wix', 'Drag-and-drop for beginners, including e-commerce.', 'Drag-and-drop for beginners, including e-commerce. Best for: best for quick small biz sites, stores, bookings.. Pricing: Free; Core $16/mo; Business $27/mo.', 'Website Creation', 'freemium', 'low', 4.5, 'https://wix.com', false),
  ('WeWeb', 'weweb', 'Backend-agnostic visual builder with AI UI generation; pairs well with Xano for scale.', 'Backend-agnostic visual builder with AI UI generation; pairs well with Xano for scale. Best for: scales with Xano for enterprise apps/portals.. Pricing: Basic $49/mo weweb.', 'Website Creation', 'paid', 'medium', 4.5, 'https://weweb.io', false),
  ('Xano', 'xano', 'Headless backend for APIs and databases; modular for complex apps.', 'Headless backend for APIs and databases; modular for complex apps. Best for: modular for complex logic-heavy apps/SaaS backends.. Pricing: Free tier; Launch $99/mo.', 'Website Creation', 'freemium', 'high', 4.5, 'https://xano.com', false),
  ('Noloco', 'noloco', 'Builds client portals and internal tools from Airtable data.', 'Builds client portals and internal tools from Airtable data. Best for: ideal for client extranets, CRM frontends.. Pricing: Free; Pro $49/mo.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://noloco.io', false),
  ('Ycode', 'ycode', 'Drag-and-drop with database and CMS; fast for MVPs.', 'Drag-and-drop with database and CMS; fast for MVPs. Best for: fast MVPs, dynamic sites with memberships.. Pricing: Starter $15/mo.', 'Website Creation', 'paid', 'low', 4.5, 'https://ycode.com', false),
  ('Saatosa', 'saatosa', 'AI/Web3 templates for SaaS sites; zero-code complex UIs.', 'AI/Web3 templates for SaaS sites; zero-code complex UIs. Best for: zero-code complex UIs/dApps.. Pricing: Not specified alphadesignpro.substack.', 'Website Creation', 'unknown', 'medium', 4.5, 'https://saatosa.com', false),
  ('Webnode', 'webnode', 'Multilingual sites with e-commerce; beginner-friendly drag-drop.', 'Multilingual sites with e-commerce; beginner-friendly drag-drop. Best for: beginner drag-drop for global SMBs.. Pricing: Free; Standard $12/mo webnode.', 'Website Creation', 'freemium', 'low', 4.5, 'https://webnode.com', false),
  ('AppGyver', 'appgyver', 'Free drag-and-drop with logic flows; deploys to web/mobile, blends no-code/pro-code for enterprises.', 'Free drag-and-drop with logic flows; deploys to web/mobile, blends no-code/pro-code for enterprises. Best for: web/mobile enterprise apps blending no/low-code.. Pricing: Free (acquired by SAP) creatorconcepts.co.', 'Website Creation', 'free', 'low', 4.5, 'https://appgyver.com', false),
  ('Caspio', 'caspio', 'Database-driven for quick apps; excels in fast implementation without heavy setup.', 'Database-driven for quick apps; excels in fast implementation without heavy setup. Best for: compliance-heavy forms/portals.. Pricing: Free trial; Basic $60/mo euroamerican.', 'Website Creation', 'freemium', 'high', 4.5, 'https://caspio.com', false),
  ('Appsmith', 'appsmith', 'Open-source for dashboards/internal tools; highly flexible with community support.', 'Open-source for dashboards/internal tools; highly flexible with community support. Best for: flexible internal apps/community extensions.. Pricing: Free (open-source); Cloud $20/mo.', 'Website Creation', 'freemium', 'low', 4.5, 'https://appsmith.com', false),
  ('Backendless', 'backendless', 'Advanced data/infra control; codeless backend with visual API builder.', 'Advanced data/infra control; codeless backend with visual API builder. Best for: advanced data/infra for scalable apps.. Pricing: Free; Pro $25/mo radixweb.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://backendless.com', false),
  ('Momen', 'momen', 'AI-native app building; seamless integration for intelligent features.', 'AI-native app building; seamless integration for intelligent features. Best for: intelligent full-stack apps.. Pricing: Free tier; Pro $29/mo zapier.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://momen.app', false),
  ('Bildr', 'bildr', 'Custom workflows and visuals; fast for interactive sites with pro features.', 'Custom workflows and visuals; fast for interactive sites with pro features. Best for: interactive pro sites.. Pricing: Personal $19/mo.', 'Website Creation', 'paid', 'low', 4.5, 'https://bildr.com', false),
  ('Loopple', 'loopple', 'Template-driven with AI; quick for SaaS-style web apps and landing pages.', 'Template-driven with AI; quick for SaaS-style web apps and landing pages. Best for: quick agency builds.. Pricing: Templates $99+ youtube.', 'Website Creation', 'paid', 'high', 4.5, 'https://loopple.com', false),
  ('Supabase', 'supabase', 'Open-source Firebase alternative with real-time Postgres DB, auth, and APIs for data-heavy apps.', 'Open-source Firebase alternative with real-time Postgres DB, auth, and APIs for data-heavy apps. Best for: real-time DB/auth for data-heavy apps.. Pricing: Free; Pro $25/mo radixweb.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://supabase.com', false),
  ('Appwrite', 'appwrite', 'Self-hosted backend for user auth, storage, and functions; highly customizable for privacy-focused projects.', 'Self-hosted backend for user auth, storage, and functions; highly customizable for privacy-focused projects. Best for: privacy-focused backends.. Pricing: Free (self-hosted) radixweb.', 'Website Creation', 'free', 'low', 4.5, 'https://appwrite.io', false),
  ('Hasura', 'hasura', 'Instant GraphQL APIs on Postgres; excels in real-time queries for dashboards and SaaS.', 'Instant GraphQL APIs on Postgres; excels in real-time queries for dashboards and SaaS. Best for: real-time SaaS/dashboards.. Pricing: Free; Cloud $99/mo radixweb.', 'Website Creation', 'freemium', 'high', 4.5, 'https://hasura.io', false),
  ('Wappler', 'wappler', 'Desktop app for full-stack sites with mobile/desktop export; pro-code extensions for power users.', 'Desktop app for full-stack sites with mobile/desktop export; pro-code extensions for power users. Best for: mobile/export with pro extensions.. Pricing: $39/mo (desktop) reddit.', 'Website Creation', 'paid', 'medium', 4.5, 'https://wappler.io', false),
  ('UI Bakery', 'ui-bakery', 'Internal tools and admin panels with AI-assisted builds; strong for business dashboards.', 'Internal tools and admin panels with AI-assisted builds; strong for business dashboards. Best for: business internal tools.. Pricing: Free; Pro $49/mo uibakery.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://uibakery.io', false),
  ('Shipper', 'shipper', 'AI-driven full web apps with payments and logic; tested for quick SaaS launches.', 'AI-driven full web apps with payments and logic; tested for quick SaaS launches. Best for: quick SaaS launches.. Pricing: Usage-based ~$20/mo lamatic.', 'Website Creation', 'usage-based', 'low', 4.5, 'https://shipper.now', false),
  ('Flatlogic', 'flatlogic', 'Full-stack generator with React/Vue templates; deploys database apps in minutes.', 'Full-stack generator with React/Vue templates; deploys database apps in minutes. Best for: instant DB apps.. Pricing: One-time $69+ flatlogic.', 'Website Creation', 'one-time', 'high', 4.5, 'https://flatlogic.com', false),
  ('Jimdo', 'jimdo', 'AI site creator with free tier; strong for multilingual SMB sites and quick edits.', 'AI site creator with free tier; strong for multilingual SMB sites and quick edits. Best for: multilingual quick edits.. Pricing: Free; Play $15/mo zapier.', 'Website Creation', 'freemium', 'low', 4.5, 'https://jimdo.com', false),
  ('Neo Sites', 'neo-sites', 'Prompt-based AI builder for business/landing pages; minimal setup with hosting.', 'Prompt-based AI builder for business/landing pages; minimal setup with hosting. Prompt AI for landings/business pages. Pricing: Usage-based titan.', 'Website Creation', 'usage-based', 'medium', 4.5, 'https://neosites.com', false),
  ('Duda', 'duda', 'Agency-focused with white-label; excels in client sites with SEO and mobile optimization.', 'Agency-focused with white-label; excels in client sites with SEO and mobile optimization. Best for: SEO/mobile optimization.. Pricing: Basic $19/mo youtube.', 'Website Creation', 'paid', 'low', 4.5, 'https://duda.co', false),
  ('Unbounce', 'unbounce', 'Landing page specialist with AI optimization; A/B testing for conversion apps.', 'Landing page specialist with AI optimization; A/B testing for conversion apps. Best for: A/B conversion optimization.. Pricing: Build $99/mo youtube.', 'Website Creation', 'paid', 'high', 4.5, 'https://unbounce.com', false),
  ('Lovable', 'lovable', 'AI full-stack builder for MVPs; exports clean GitHub code for startups.', 'AI full-stack builder for MVPs; exports clean GitHub code for startups. Best for: startup prototyping.. Pricing: Beta free; Pro ~$20/mo ideaproof.', 'Website Creation', 'freemium', 'low', 4.5, 'https://lovable.dev', false),
  ('Bolt', 'bolt', 'Browser-based AI app generator by StackBlitz; instant previews with Next.js support.', 'Browser-based AI app generator by StackBlitz; instant previews with Next.js support. Best for: Next.js previews.. Pricing: Free beta nocode.', 'Website Creation', 'free', 'low', 4.5, 'https://bolt.new', false),
  ('Glide', 'glide', 'Turns Google Sheets into mobile/web apps; excels in quick data-driven prototypes.', 'Turns Google Sheets into mobile/web apps; excels in quick data-driven prototypes. Best for: data prototypes/mobile.. Pricing: Free; Starter $25/mo blaze.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://glideapps.com', false),
  ('Bravo Studio', 'bravo-studio', 'Converts Figma designs to native apps; no-code bridge for designers.', 'Converts Figma designs to native apps; no-code bridge for designers. Best for: designer bridge.. Pricing: Free; Pro $21/mo blaze.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://bravostudio.app', false),
  ('Playcode', 'playcode', 'AI chat-to-website with React/Vue output; agency-grade without templates.', 'AI chat-to-website with React/Vue output; agency-grade without templates. Best for: React/Vue agency output.. Pricing: Free tier playcode.', 'Website Creation', 'free', 'low', 4.5, 'https://playcode.io', false),
  ('NocoBase', 'nocobase', 'Open-source, lightweight platform for extensible apps with AI data handling; self-hosted focus.', 'Open-source, lightweight platform for extensible apps with AI data handling; self-hosted focus. Best for: self-hosted AI data.. Pricing: Free (open-source) nocobase.', 'Website Creation', 'free', 'low', 4.5, 'https://nocobase.com', false),
  ('FlutterFlow', 'flutterflow', 'Drag-and-drop for web/mobile with Firebase integration and code export; self-hosting via CLI.', 'Drag-and-drop for web/mobile with Firebase integration and code export; self-hosting via CLI. Best for: code export/self-host.. Pricing: Free; Standard $30/mo nocodefinder.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://flutterflow.io', false),
  ('Launchpad', 'launchpad', 'AI-powered orchestration for production workflows; enterprise-grade no-code backend.', 'AI-powered orchestration for production workflows; enterprise-grade no-code backend. Best for: production backends.. Pricing: Enterprise custom launchpad.', 'Website Creation', 'enterprise', 'medium', 4.5, 'https://launchpad.i', false),
  ('ToolJet', 'tooljet', 'Open-source for internal tools/dashboards; connects 50+ data sources with AI query builder.', 'Open-source for internal tools/dashboards; connects 50+ data sources with AI query builder. Best for: 50+ data sources/AI queries.. Pricing: Free; Team $25/mo dev.', 'Website Creation', 'freemium', 'medium', 4.5, 'https://tooljet.com', false),
  ('NocoDB', 'nocodb', 'Turns spreadsheets into smart databases; self-hosted with API/GraphQL for web apps.', 'Turns spreadsheets into smart databases; self-hosted with API/GraphQL for web apps. Best for: self-hosted API/GraphQL.. Pricing: Free (open-source) dev.', 'Website Creation', 'free', 'low', 4.5, 'https://nocodb.com', false),
  ('Budibase', 'budibase', 'Open-source platform for apps/dashboards; CouchDB backend with self-hosting and automation.', 'Open-source platform for apps/dashboards; CouchDB backend with self-hosting and automation. Best for: CouchDB self-hosting/automation.. Pricing: Free; Growth $10/mo dev.', 'Website Creation', 'freemium', 'low', 4.5, 'https://budibase.com', false);

-- Total: 41 tools inserted


-- ============================================
-- BuilderStack: Analytics tools seed data
-- Category: Analytics
-- ============================================
 
-- Insert analytics tools (skip duplicates via ON CONFLICT)
INSERT INTO tools (name, slug, short_description, long_description, category, pricing_model, budget_level, rating, website_link, is_sponsored) VALUES
  ('Metabase', 'metabase', 'Visual charts atop databases; self-service BI for', 'Visual charts atop databases; self-service BI for. Open-source BI with SQL-free question builder, 40+ chart types, dashboard embedding, row-level security (Pro+), SSO/SAML (Enterprise), supports 15+ databases, admin audit logs, scheduled reports, public', 'Analytics', 'freemium', 'high', 4.5, '', false),
  ('Power BI', 'power-bi', 'Drag-drop reports from any source; enterprise', 'Drag-drop reports from any source; enterprise. Microsoft''s no-code BI with Power Query ETL, 100+ connectors (Excel, SQL, Salesforce), AI visuals (key influencers, decomposition trees), paginated reports, dataflows, gateway for on-prem, row-level security, mobile', 'Analytics', 'freemium', 'low', 4.5, '', false),
  ('Google Looker Studio', 'google-looker-studio', 'Google ecosystem BI; real-time marketing', 'Google ecosystem BI; real-time marketing. Formerly Data Studio; BigQuery-optimized with community connectors, blended data, calculated fields, cross-filtering, drill-downs, themes, real-time collaboration, 500+ templates, date range controls, button', 'Analytics', 'free', 'low', 4.5, '', false),
  ('Superset', 'superset', 'Modern BI/SQL IDE; advanced', 'Modern BI/SQL IDE; advanced. Airbnb-originated petabyte-scale BI; SQLAlchemy 50+ DB connectors, semantic layer (virtual metrics/datasets), 40+ viz types, dashboard filters, Jinja templating, CSV/JSON support, role-based access technology.amis+1', 'Analytics', 'free', 'low', 4.5, '', false),
  ('Index', 'index', 'AI natural language queries; instant charts for SaaS', 'AI natural language queries; instant charts for SaaS. IndexAI converts plain English to SQL/charts with guardrails against costly queries, dashboard sharing, saved questions, unified data sources, revenue metrics focus', 'Analytics', 'paid', 'medium', 4.5, '', false),
  ('ChartPixel', 'chartpixel', 'AI data cleaning/visuals; auto-charts for', 'AI data cleaning/visuals; auto-charts for. AI-powered with real-time processing, customizable dashboards, predictive analytics, ML integration, data import/export, geospatial analysis, natural language query, custom alerts, automated', 'Analytics', 'usage-based', 'medium', 4.5, '', false),
  ('Knack', 'knack', 'No-code app analytics; custom database', 'No-code app analytics; custom database. Database app platform with built-in reporting/visualization, trend identification, real-time performance monitoring, actionable insights without IT', 'Analytics', 'paid', 'medium', 4.5, '', false),
  ('Grafana', 'grafana', 'Time-series dashboards; monitoring/IoT', 'Time-series dashboards; monitoring/IoT. No-code query builder evolution to queryless investigations, 100+ plugins, Loki/Prometheus integration, alerting, annotations, transformations, Explore mode for ad-hoc', 'Analytics', 'freemium', 'low', 4.5, '', false),
  ('KNIME', 'knime', 'Visual data science workflows; ML', 'Visual data science workflows; ML. Drag-drop nodes for ETL/ML, 300+ connectors, Python/R integration, workflow sharing, big data processing (Spark), collaborative', 'Analytics', 'free', 'low', 4.5, '', false),
  ('Graphite Note', 'graphite-note', 'No-code predictive analytics; AutoML', 'No-code predictive analytics; AutoML. Automated ML models, prescriptive actions, time-series forecasting, business-ready predictions without data science', 'Analytics', 'usage-based', 'medium', 4.5, '', false),
  ('Livedocs', 'livedocs', 'Interactive AI charts; real-time', 'Interactive AI charts; real-time. AI-driven interactive visualizations, real-time data exploration, collaborative reporting for', 'Analytics', 'paid', 'low', 4.5, '', false),
  ('ChartBlocks', 'chartblocks', 'Live chart automation; API/spreadsheet', 'Live chart automation; API/spreadsheet. Embeddable live charts, real-time data feeds, API connectors, scheduled refreshes, responsive', 'Analytics', 'freemium', 'medium', 4.5, '', false),
  ('Querio', 'querio', 'Natural language agentic notebooks; plain English SQL', 'Natural language agentic notebooks; plain English SQL. Agentic notebooks translating business questions to SQL, enterprise-grade security, scalable', 'Analytics', 'enterprise', 'low', 4.5, '', false),
  ('Apache Zeppelin', 'apache-zeppelin', 'Multi-language notebooks; Spark/SQL', 'Multi-language notebooks; Spark/SQL. Web-based notebook with Spark/Flink/SQL interpreters, dynamic forms, collaborative', 'Analytics', 'free', 'low', 4.5, '', false),
  ('BlazeSQL', 'blazesql', 'AI SQL generation + viz; natural language', 'AI SQL generation + viz; natural language. Chat-to-SQL with visualization, database connections, query optimization, non-technical', 'Analytics', 'usage-based', 'medium', 4.5, '', false),
  ('Luminary', 'luminary', 'AI conversational analytics; chat', 'AI conversational analytics; chat. Chat interface for data analysis, marketing/sales insights, natural language', 'Analytics', 'paid', 'medium', 4.5, '', false),
  ('Evidence', 'evidence', 'Markdown-based reports; SQL automated', 'Markdown-based reports; SQL automated. Site generator from Markdown/SQL, automated charts, public dashboards, version control', 'Analytics', 'free', 'low', 4.5, '', false),
  ('Lightdash', 'lightdash', 'dbt + LookML explorer; modern warehouse', 'dbt + LookML explorer; modern warehouse. dbt integration, semantic layer, LookML explorer, YAML models, warehouse-native', 'Analytics', 'freemium', 'medium', 4.5, '', false),
  ('Matomo', 'matomo', 'Privacy-first web analytics; GDPR GA', 'Privacy-first web analytics; GDPR GA. 100+ reports, heatmaps, A/B testing, form analytics, e-commerce tracking, API, plugins', 'Analytics', 'freemium', 'low', 4.5, '', false),
  ('Shynet', 'shynet', 'Cookie-less detailed analytics; lightweight', 'Cookie-less detailed analytics; lightweight. Self-hosted, no cookies/PII, unique visitor tracking, real-time dashboard, simple embed', 'Analytics', 'free', 'low', 4.5, '', false),
  ('Umami', 'umami', 'Simple privacy-first dashboards; real-time', 'Simple privacy-first dashboards; real-time. Minimalist GA alternative, event tracking, filters, custom dimensions, teams/projects', 'Analytics', 'freemium', 'low', 4.5, '', false),
  ('Coupler.io', 'couplerio', 'No-code data sync/visuals; 800+ source', 'No-code data sync/visuals; 800+ source. Automated data imports to Sheets/Looker/Power BI, scheduled refreshes, transformations, multi-source', 'Analytics', 'freemium', 'medium', 4.5, '', false),
  ('Flow Immersive', 'flow-immersive', 'AR/3D data viz; immersive web/XR', 'AR/3D data viz; immersive web/XR. 3D/AR visualizations, spatial data analysis, collaborative XR sessions for enterprise', 'Analytics', 'enterprise', 'medium', 4.5, '', false),
  ('Metrical', 'metrical', 'Lightweight real-time web metrics; simple startup', 'Lightweight real-time web metrics; simple startup. Real-time pageviews/events, goal tracking, custom properties, embed code, no complex', 'Analytics', 'free', 'low', 4.5, '', false)
ON CONFLICT (slug) DO NOTHING;
 
-- Total: 24 new analytics tools


-- ============================================
-- BuilderStack: CRM tools seed data
-- Category: CRM
-- ============================================
 
-- Insert CRM tools (skip duplicates via ON CONFLICT)
INSERT INTO tools (name, slug, short_description, long_description, category, pricing_model, budget_level, rating, website_link, is_sponsored) VALUES
  ('HubSpot CRM', 'hubspot-crm', 'Lead tracking, emails, pipelines; small biz sales/marketing', 'Lead tracking, emails, pipelines; small biz sales/marketing. Free core CRM with 1M+ contacts, email sequences, meeting scheduler, forms, live chat, 1,800+ app marketplace, shared inbox, reporting dashboards, sales automation', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('Airtable', 'airtable', 'Flexible databases as CRM; custom views, teams', 'Flexible databases as CRM; custom views, teams. Spreadsheet-database hybrid with linked records, 50+ field types (kanban, calendar, gallery), Airtable Interfaces, 50+ native integrations + Zapier, granular permissions', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('Zoho CRM', 'zoho-crm', 'AI automation, analytics; customizable SMB sales', 'AI automation, analytics; customizable SMB sales. Zia AI assistant, lead scoring, workflow automation, omnichannel (email, phone, social, chat), mobile app, Canvas view customization, sales signals timeline', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('monday.com CRM', 'mondaycom-crm', 'Visual pipelines, project ties; team collaboration', 'Visual pipelines, project ties; team collaboration. Work OS with sales CRM templates, timeline/gantt views, automation center, 200+ integrations, custom columns, sales forecasting, deal history tracking', 'CRM', 'paid', 'low', 4.5, '', false),
  ('Ninox', 'ninox', 'Templates/kanban; lead mgmt, quick pipelines', 'Templates/kanban; lead mgmt, quick pipelines. Native Mac/iOS app with scriptable automation, relational database, offline sync, 500+ templates, real-time collaboration, barcode/QR scanning', 'CRM', 'paid', 'low', 4.5, '', false),
  ('Streak', 'streak', 'Gmail-integrated CRM; email-first sales tracking', 'Gmail-integrated CRM; email-first sales tracking. Gmail sidebar CRM with pipeline boards, email tracking, snippets, mail merge, shared inboxes, Zapier integration, Chrome extension', 'CRM', 'paid', 'low', 4.5, '', false),
  ('Pipefy', 'pipefy', 'Process automation; workflow-heavy operations', 'Process automation; workflow-heavy operations. Kanban-based process automation, conditional routing, SLAs, dynamic forms, 100+ templates, API access, real-time notifications', 'CRM', 'freemium', 'medium', 4.5, '', false),
  ('Adalo', 'adalo', 'Mobile CRM apps; custom interfaces', 'Mobile CRM apps; custom interfaces. Native mobile app builder with push notifications, GPS, barcode scanning, Airtable/database connectors, white-label branding, app store publishing', 'CRM', 'freemium', 'medium', 4.5, '', false),
  ('Zoho Creator', 'zoho-creator', 'App builder for CRM; low-code forms/workflows', 'App builder for CRM; low-code forms/workflows. Drag-drop app builder with mobile preview, GPS fields, barcode scanning, workflow automation, external database connectors, white-label portals', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('Insightly', 'insightly', 'Pipeline/project mgmt; service-focused SMBs', 'Pipeline/project mgmt; service-focused SMBs. Built-in project management, relationship linking, custom fields, workflow automation, embedded forms, sales forecasting', 'CRM', 'paid', 'medium', 4.5, '', false),
  ('Stacker', 'stacker', 'AI-custom CRMs from prompts; scaling portals', 'AI-custom CRMs from prompts; scaling portals. AI-powered Airtable builder, bidirectional sync, user permissions, Stripe payments, Zapier/Make integrations, custom domains', 'CRM', 'freemium', 'high', 4.5, '', false),
  ('Barawave', 'barawave', 'AI workflows/integrations; scalable interactions', 'AI workflows/integrations; scalable interactions. AI-native platform with voice/video agents, n8n workflows, custom GPTs, Twilio telephony, Stripe payments', 'CRM', 'enterprise', 'medium', 4.5, '', false),
  ('Zams', 'zams', 'Natural language CRM orchestration; B2B sales', 'Natural language CRM orchestration; B2B sales. AI agent platform with CRM orchestration, natural language processing, multi-channel communication, sales automation', 'CRM', 'enterprise', 'medium', 4.5, '', false),
  ('Baserow', 'baserow', 'Spreadsheet-style simple CRM; lightweight', 'Spreadsheet-style simple CRM; lightweight. Airtable alternative with real-time collaboration, plugin system, API access, row-level permissions, database views', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('FLOWii', 'flowii', 'All-in-one CRM/ERP; freelancers/SMEs', 'All-in-one CRM/ERP; freelancers/SMEs. Eastern European all-in-one with invoicing, projects, time tracking, kanban, client portal, multi-language support', 'CRM', 'paid', 'low', 4.5, '', false),
  ('Agilebase', 'agilebase', 'AI-powered database-to-CRM; citizen developers', 'AI-powered database-to-CRM; citizen developers. Power Platform connector with no-code data modeling, Power Automate flows, Teams/SharePoint integration', 'CRM', 'enterprise', 'medium', 4.5, '', false),
  ('Creatio', 'creatio', 'AI-native workflows; enterprise sales/marketing', 'AI-native workflows; enterprise sales/marketing. Studio-based no-code with process designer, marketplace templates, Copilot AI, omnichannel communications', 'CRM', 'paid', 'medium', 4.5, '', false),
  ('Atomic CRM', 'atomic-crm', 'Lightweight flexible data model; custom CRMs', 'Lightweight flexible data model; custom CRMs. Modern React-based CRM with automated deployment, flexible schema, developer extensibility', 'CRM', 'free', 'low', 4.5, '', false),
  ('EspoCRM', 'espocrm', 'Modular entity management; complex pipelines', 'Modular entity management; complex pipelines. Extension framework, entity-relationship designer, dynamic logic, record access control, layout manager', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('SuiteCRM', 'suitecrm', 'Mature SugarCRM fork; established SMBs', 'Mature SugarCRM fork; established SMBs. Campaigns, quotes, contracts, forecasting, document merge, portal module, telephony integration', 'CRM', 'free', 'low', 4.5, '', false),
  ('Odoo CRM', 'odoo-crm', 'ERP/CRM integration; growing businesses', 'ERP/CRM integration; growing businesses. 30+ official apps, pipeline automation, meeting scheduler, email integration, VoIP, reporting', 'CRM', 'freemium', 'medium', 4.5, '', false),
  ('ERPNext', 'erpnext', 'Manufacturing/services CRM; project accounting', 'Manufacturing/services CRM; project accounting. Manufacturing module, quality inspection, maintenance, projects, accounting, asset management', 'CRM', 'free', 'low', 4.5, '', false),
  ('Axelor', 'axelor', 'Business apps suite; BPM workflows', 'Business apps suite; BPM workflows. BPM designer, business app studio, multi-company, multi-language, mobile apps, web portal', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('Budibase CRM', 'budibase-crm', 'Internal tool builder; spreadsheet automations', 'Internal tool builder; spreadsheet automations. Low-code internal apps platform, 50+ data connectors, custom automations, role-based access', 'CRM', 'free', 'low', 4.5, '', false),
  ('Directus', 'directus', 'Headless CMS/CRM; API-first data layer', 'Headless CMS/CRM; API-first data layer. Instant REST/GraphQL APIs, no-code dashboard builder, granular permissions, file management', 'CRM', 'freemium', 'medium', 4.5, '', false),
  ('Frappe CRM', 'frappe-crm', 'Frappe Framework CRM; growing businesses', 'Frappe Framework CRM; growing businesses. Frappe/ERPNext ecosystem, DocType customization, workflow automation, client scripts', 'CRM', 'free', 'low', 4.5, '', false),
  ('BottleCRM', 'bottlecrm', 'Modern SMB CRM; zero-cost enterprise', 'Modern SMB CRM; zero-cost enterprise. Multi-tenant SaaS-ready, modern UI, activity management, document storage', 'CRM', 'free', 'low', 4.5, '', false),
  ('Pipedrive', 'pipedrive', 'Sales-focused pipelines; revenue closing', 'Sales-focused pipelines; revenue closing. Smart email BCC, AI sales assistant, visual pipeline, deal rotator, revenue forecasting', 'CRM', 'paid', 'low', 4.5, '', false),
  ('Twenty', 'twenty', 'Modern lightweight CRM; developer-friendly', 'Modern lightweight CRM; developer-friendly. TypeScript stack, extensible schema, modern React UI, self-hosting support', 'CRM', 'free', 'low', 4.5, '', false),
  ('OroCRM', 'orocrm', 'B2B multichannel sales; complex commerce', 'B2B multichannel sales; complex commerce. Multi-channel order management, customer segments, promotions, Magento/Sylius sync', 'CRM', 'free', 'low', 4.5, '', false),
  ('Yetiforce', 'yetiforce', 'Advanced modules/workflows; telephony', 'Advanced modules/workflows; telephony. Knowledge base, service contracts, telephony integration, customer portal', 'CRM', 'free', 'low', 4.5, '', false),
  ('CiviCRM', 'civicrm', 'Nonprofit/donor management; mission-driven', 'Nonprofit/donor management; mission-driven. Drupal/WordPress plugin, events, memberships, grants, activities, case management', 'CRM', 'free', 'low', 4.5, '', false),
  ('Mautic', 'mautic', 'Marketing automation CRM; lead nurturing', 'Marketing automation CRM; lead nurturing. Email builder, landing pages, web tracking, lead scoring, segmentation', 'CRM', 'free', 'low', 4.5, '', false),
  ('Vtiger', 'vtiger', 'Sales/support integration; service businesses', 'Sales/support integration; service businesses. Helpdesk module, project management, inventory, service contracts', 'CRM', 'freemium', 'low', 4.5, '', false),
  ('Fat Free CRM', 'fat-free-crm', 'Ruby lightweight CRM; startups', 'Ruby lightweight CRM; startups. Ruby on Rails, simple contact/opportunity model, jQuery UI', 'CRM', 'free', 'low', 4.5, '', false),
  ('Krayin', 'krayin', 'Headless e-commerce CRM; online stores', 'Headless e-commerce CRM; online stores. Laravel/Vue.js, GraphQL API, headless commerce, customer portal', 'CRM', 'free', 'low', 4.5, '', false),
  ('Zurmo', 'zurmo', 'Gamified sales workflows; team motivation', 'Gamified sales workflows; team motivation. Gamification engine, workflow automation, social features', 'CRM', 'free', 'low', 4.5, '', false),
  ('Hulkes CRM', 'hulkes-crm', 'Finnish lightweight CRM; solopreneurs', 'Finnish lightweight CRM; solopreneurs. Simple pipeline management, contact tracking', 'CRM', 'free', 'low', 4.5, '', false),
  ('RescueCRM', 'rescuecrm', 'Agile contact management; dev teams', 'Agile contact management; dev teams. Ruby on Rails, agile methodology focus', 'CRM', 'free', 'low', 4.5, '', false),
  ('webCRM', 'webcrm', 'UK all-in-one; GDPR European SMBs', 'UK all-in-one; GDPR European SMBs. GDPR compliance, marketing automation, sales forecasting', 'CRM', 'paid', 'low', 4.5, '', false)
ON CONFLICT (slug) DO NOTHING;
 
-- Total: 40 new CRM tools