// BuilderStack — Tools page data
// Three categories, 4 tools each.
// Rank 1 = gold (editorial #1), 2 = silver, 3 = bronze, 4 = sponsored.

// Per-chat context — what brought the user here, what they need.
const CHATS_CTX = {
  crm: {
    title: 'CRM for tracking client conversations',
    summary: 'A lightweight CRM for a 2–5 person team, mostly inbound leads from web forms and referrals. Budget under $50/seat/month. No need for forecasting or marketing automation.',
    signals: [
      { label: 'Team size', value: '2–5 people' },
      { label: 'Lead sources', value: 'Inbound forms, referrals' },
      { label: 'Budget', value: '< $50/seat/mo' },
      { label: 'Must avoid', value: 'Salesforce-style complexity' },
    ],
    categoryId: 'crm',
  },
  web: {
    title: 'Portfolio site for my consulting practice',
    summary: 'A polished, low-maintenance portfolio site for a solo consultant. Updated occasionally from a phone. Should look premium without requiring code.',
    signals: [
      { label: 'Project', value: 'Consulting portfolio' },
      { label: 'Edit comfort', value: 'No code preferred' },
      { label: 'Update freq.', value: 'Occasional, mobile' },
      { label: 'Priority', value: 'Premium look' },
    ],
    categoryId: 'web',
  },
  ana: {
    title: 'Analytics for the new landing page',
    summary: 'Privacy-first analytics for a B2B landing page at ~30k pageviews/month. Hosted is fine. Cookie banners are a hard no.',
    signals: [
      { label: 'Site type', value: 'B2B landing page' },
      { label: 'Traffic', value: '~30k pageviews/mo' },
      { label: 'Hosting', value: 'Hosted is fine' },
      { label: 'Hard no', value: 'Cookie banners' },
    ],
    categoryId: 'analytics',
  },
};

const TOOLS_DATA = {
  categories: [
    {
      id: 'crm',
      title: 'CRM',
      blurb: 'Lightweight pipelines for small teams who want to track real conversations, not enterprise dashboards.',
      tools: [
        {
          rank: 1,
          name: 'Attio',
          logo: 'A',
          logoBg: '#0F172A',
          oneliner: 'A modern, flexible CRM that adapts to how you actually sell.',
          forYou: "Best fit for a 2–5 person team with inbound flow. Attio's data model bends to your pipeline rather than the other way around — you'll spend afternoons configuring it, not weeks.",
          users: '40,000+',
          updated: 'Apr 12, 2026',
          price: 'Free → $34/seat',
          rating: 4.8,
          tags: ['No-code customisable', 'Strong API', 'AI-native'],
          pros: ['Genuinely flexible data model', 'Beautiful, fast UI', 'Two-way email sync that works'],
          cons: ['Free plan is limited', 'No native marketing tools', 'Reporting still maturing'],
        },
        {
          rank: 2,
          name: 'Pipedrive',
          logo: 'P',
          logoBg: '#1A6F2E',
          oneliner: 'The veteran sales-first CRM. Pipeline-centric and proven.',
          forYou: "If you live in deal stages, Pipedrive is the path of least resistance. Slightly more rigid than Attio, but you'll be productive in an hour.",
          users: '100,000+',
          updated: 'Apr 9, 2026',
          price: '$14 → $99/seat',
          rating: 4.6,
          tags: ['Pipeline-first', 'Mature ecosystem', 'Mobile-strong'],
          pros: ['Fastest setup', 'Huge integrations library', 'Great mobile app'],
          cons: ['Dated UI in places', 'Custom fields cost extra', 'Reports gated to higher tiers'],
        },
        {
          rank: 3,
          name: 'Folk',
          logo: 'F',
          logoBg: '#2563EB',
          oneliner: 'Contact-first CRM for relationship-led teams.',
          forYou: 'If your sales motion is "trusted introductions" more than "pipeline math", Folk is built for that. Lighter than Attio, friendlier than Pipedrive.',
          users: '15,000+',
          updated: 'Mar 30, 2026',
          price: '$20 → $80/seat',
          rating: 4.5,
          tags: ['Relationship-first', 'LinkedIn import', 'Light'],
          pros: ['Effortless contact import', 'Calm, simple UI', 'Good for solo + small'],
          cons: ['Less powerful for deal-heavy teams', 'API less mature', 'Newer brand'],
        },
        {
          rank: 4,
          sponsored: true,
          name: 'Close',
          logo: 'C',
          logoBg: '#0EA5E9',
          oneliner: 'CRM built around the call and the inbox.',
          forYou: 'Solid choice if your team lives on the phone. We list this fourth — it\'s a paid placement, but the product genuinely competes with the editorial picks above.',
          users: '60,000+',
          updated: 'Apr 2, 2026',
          price: '$49 → $139/seat',
          rating: 4.4,
          tags: ['Built-in calling', 'Power-dialer', 'Email sequences'],
          pros: ['Best-in-class calling', 'SMS + email built in', 'Workflows are powerful'],
          cons: ['Pricier per seat', 'Overkill for inbound-only', 'Less flexible data model'],
        },
      ],
    },
    {
      id: 'web',
      title: 'Website builders',
      blurb: 'Get a polished site live in days, not months — without locking yourself into a framework you\'ll outgrow.',
      tools: [
        {
          rank: 1,
          name: 'Framer',
          logo: 'F',
          logoBg: '#0F172A',
          oneliner: 'Design-tool-first website builder. Pixel control with real CMS.',
          forYou: 'Perfect for a portfolio or marketing site where design quality matters. You design like Figma, ship like a pro. Phone-editable via the dashboard.',
          users: '500,000+',
          updated: 'Apr 15, 2026',
          price: 'Free → $30/site',
          rating: 4.8,
          tags: ['Visual editor', 'CMS', 'Fast hosting'],
          pros: ['Genuinely beautiful results', 'Real CMS, not a fake one', 'Lightning-fast builds'],
          cons: ['Pricey at scale', 'No deep e-commerce', 'Vendor lock-in for advanced sites'],
        },
        {
          rank: 2,
          name: 'Webflow',
          logo: 'W',
          logoBg: '#3B82F6',
          oneliner: 'The professional standard for visually-built marketing sites.',
          forYou: 'If you want maximum power without code, Webflow is unmatched. Steeper learning curve than Framer; bigger ceiling.',
          users: '3.5M+',
          updated: 'Apr 8, 2026',
          price: '$14 → $39/site',
          rating: 4.6,
          tags: ['Pro-grade', 'Big ecosystem', 'CMS + commerce'],
          pros: ['Massive plugin/template library', 'Powerful CMS', 'Production-grade hosting'],
          cons: ['Learning curve', 'Pricing tiers can confuse', 'Designer mindset required'],
        },
        {
          rank: 3,
          name: 'Cargo',
          logo: 'C',
          logoBg: '#7C3AED',
          oneliner: 'Editorial portfolio platform with strong design DNA.',
          forYou: 'If your site is mostly imagery and writing, Cargo gets out of the way. Lighter than Framer, more opinionated than Webflow.',
          users: '80,000+',
          updated: 'Mar 24, 2026',
          price: '$13/mo flat',
          rating: 4.4,
          tags: ['Editorial', 'Type-driven', 'Indie'],
          pros: ['Beautiful default typography', 'Flat pricing', 'Strong creative community'],
          cons: ['Limited for marketing sites', 'No native CMS extras', 'Smaller plugin world'],
        },
        {
          rank: 4,
          sponsored: true,
          name: 'Squarespace',
          logo: 'S',
          logoBg: '#000000',
          oneliner: 'All-in-one classic — templates, hosting, domain, email, commerce.',
          forYou: 'A safe, well-supported choice if you want one bill and one dashboard. Listed fourth because we believe the picks above produce better-looking, faster sites.',
          users: '4M+',
          updated: 'Apr 4, 2026',
          price: '$16 → $52/mo',
          rating: 4.3,
          tags: ['All-in-one', 'Mature support', 'Commerce-ready'],
          pros: ['Easiest end-to-end setup', 'Solid templates', 'Real human support'],
          cons: ['Less design freedom', 'Slower than Framer/Webflow', 'Locked-in stack'],
        },
      ],
    },
    {
      id: 'analytics',
      title: 'Analytics',
      blurb: 'Know what your visitors do without strapping a cookie banner to your front page.',
      tools: [
        {
          rank: 1,
          name: 'Plausible',
          logo: 'P',
          logoBg: '#0F172A',
          oneliner: 'Privacy-first, cookie-free analytics. One simple dashboard.',
          forYou: 'Hits every requirement: hosted, cookie-free, GDPR-ready, simple. At ~30k pageviews/mo you\'ll be on their cheapest paid tier ($9/mo).',
          users: '14,000+',
          updated: 'Apr 16, 2026',
          price: '$9 → $69/mo',
          rating: 4.8,
          tags: ['Cookie-free', 'GDPR', 'Lightweight script'],
          pros: ['Tiny script (<1KB)', 'Single shareable dashboard', 'Open-source option'],
          cons: ['Less granular than GA4', 'No session replay', 'Funnels gated to higher tier'],
        },
        {
          rank: 2,
          name: 'Fathom',
          logo: 'F',
          logoBg: '#7C2D92',
          oneliner: 'Privacy analytics with a clean UI and isolated EU hosting.',
          forYou: 'Near-twin of Plausible. Pick Fathom if you specifically want EU-isolated data; pick Plausible if you want open-source as a fallback.',
          users: '10,000+',
          updated: 'Apr 11, 2026',
          price: '$15 → $90/mo',
          rating: 4.6,
          tags: ['Cookie-free', 'EU-isolated option', 'Calm UI'],
          pros: ['Easy onboarding', 'EU-only data option', 'Good email reports'],
          cons: ['Slightly pricier than Plausible', 'No self-host', 'Smaller community'],
        },
        {
          rank: 3,
          name: 'Simple Analytics',
          logo: 'S',
          logoBg: '#0EA5E9',
          oneliner: 'The simplest possible privacy-friendly tracker.',
          forYou: 'If you want one number — visitors and pageviews — and nothing more, Simple is the most honest tool here.',
          users: '8,000+',
          updated: 'Mar 28, 2026',
          price: '$10 → $50/mo',
          rating: 4.4,
          tags: ['Minimalist', 'Cookie-free', 'No-fuss'],
          pros: ['Truly simple', 'Fast dashboards', 'Good defaults'],
          cons: ['Limited custom events', 'No funnels', 'Niche feature set'],
        },
        {
          rank: 4,
          sponsored: true,
          name: 'PostHog',
          logo: 'P',
          logoBg: '#F97316',
          oneliner: 'Product analytics + session replay + feature flags + experiments.',
          forYou: 'Enormous platform — overkill for a landing page, but the free tier is generous. Listed fourth because it\'s broader than your stated need.',
          users: '50,000+',
          updated: 'Apr 14, 2026',
          price: 'Free → custom',
          rating: 4.5,
          tags: ['Product analytics', 'Session replay', 'Self-host'],
          pros: ['Free tier is enormous', 'All-in-one platform', 'Self-hosting option'],
          cons: ['Overkill for marketing sites', 'Steeper learning curve', 'Heavier script'],
        },
      ],
    },
  ],
};

window.TOOLS_DATA = TOOLS_DATA;
window.CHATS_CTX = CHATS_CTX;
